name: gebeyaye
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  bloc: ^8.1.3
  cached_network_image: ^3.3.1
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^6.0.4
  flutter_native_splash: ^2.3.11
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  google_sign_in: ^6.2.1
  injectable: ^2.3.2
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  lint: ^2.0.0
  injectable_generator: ^2.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/MontserratRomanSemiBold.ttf
          weight: 600
        - asset: assets/fonts/MontserratRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/MontserratRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/MontserratItalicThin.ttf
          weight: 100
        - asset: assets/fonts/MontserratRomanExtraBold.ttf
          weight: 800
        - asset: assets/fonts/MontserratRomanBold.ttf
          weight: 700
        - asset: assets/fonts/MontserratRegular.ttf
          weight: 400
        - asset: assets/fonts/MontserratSemiBold.ttf
          weight: 600
        - asset: assets/fonts/MontserratMedium.ttf
          weight: 500
        - asset: assets/fonts/MontserratLight.ttf
          weight: 300
    - family: Libre Caslon Text
      fonts:
        - asset: assets/fonts/LibreCaslonTextBold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoRomanRegular.ttf
          weight: 400
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/fonts/PlusJakartaSansRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSansSemiBold.ttf
          weight: 600
# flutter_native_splash:
#   color: "#ffffff"
#   image: assets/images/img_group_34010.png
#   color_dark: "#121212"
#   image_dark: assets/images/img_group_34010.png
#   android_12:
#     image: assets/images/img_group_34010.png
#     icon_background_color: "#ffffff"
#     image_dark: assets/images/img_group_34010.png
#     icon_background_color_dark: "#121212"
